version: '3.8'

services:
  waha:
    image: devlikeapro/waha
    container_name: waha
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      # Disable Dashboard Password completely
      - WAHA_DASHBOARD_PASSWORD=
      - WAHA_DASHBOARD_NO_PASSWORD=True
      # Disable Swagger Password completely
      - WHATSAPP_SWAGGER_PASSWORD=
      - WHATSAPP_SWAGGER_NO_PASSWORD=True
      # Disable API Key requirement completely
      - WAHA_API_KEY=
      - WAHA_NO_API_KEY=True
      # Webhook URL for Python
      - WHATSAPP_WEBHOOK_URL=http://host.docker.internal:5000/webhook
    volumes:
      # Saves your WhatsApp login permanently so you don't have to scan the QR code again if PC restarts
      - ./waha_sessions:/app/.sessions
